/**
 * Portuguese (PT-PT) word bank for crossword puzzles.
 * Words are stored in uppercase without diacritics for grid placement.
 * Clues are in PT-PT.
 */
import type { WordBankEntry } from './types';

export const wordBank: WordBankEntry[] = [
	// ─── Easy (3-5 letters) ─────────────────────────────
	{ word: 'SOL', clue: 'Astro-rei que ilumina o dia', difficulty: 'easy', category: 'natureza' },
	{ word: 'MAR', clue: 'Grande extensão de água salgada', difficulty: 'easy', category: 'natureza' },
	{ word: 'LUA', clue: 'Satélite natural da Terra', difficulty: 'easy', category: 'natureza' },
	{ word: 'RIO', clue: 'Curso de água doce', difficulty: 'easy', category: 'natureza' },
	{ word: 'COR', clue: 'Tonalidade visual como azul ou verde', difficulty: 'easy', category: 'geral' },
	{ word: 'PAZ', clue: 'Ausência de guerra ou conflito', difficulty: 'easy', category: 'geral' },
	{ word: 'REI', clue: 'Monarca soberano', difficulty: 'easy', category: 'geral' },
	{ word: 'AVE', clue: 'Animal com penas e asas', difficulty: 'easy', category: 'animais' },
	{ word: 'CHA', clue: 'Bebida quente de ervas', difficulty: 'easy', category: 'comida' },
	{ word: 'OVO', clue: 'Produto da galinha usado na cozinha', difficulty: 'easy', category: 'comida' },
	{ word: 'PEZ', clue: 'Substância resinosa escura', difficulty: 'easy', category: 'geral' },
	{ word: 'DIA', clue: 'Período de luz solar', difficulty: 'easy', category: 'tempo' },
	{ word: 'CEU', clue: 'Espaço azul acima de nós', difficulty: 'easy', category: 'natureza' },
	{ word: 'MEL', clue: 'Produto doce das abelhas', difficulty: 'easy', category: 'comida' },
	{ word: 'SAL', clue: 'Condimento branco e salgado', difficulty: 'easy', category: 'comida' },
	{ word: 'VEZ', clue: 'Ocasião ou turno', difficulty: 'easy', category: 'geral' },
	{ word: 'POR', clue: 'Preposição: colocar em cima', difficulty: 'easy', category: 'geral' },
	{ word: 'CAO', clue: 'Melhor amigo do Homem', difficulty: 'easy', category: 'animais' },
	{ word: 'PAO', clue: 'Alimento básico feito de farinha', difficulty: 'easy', category: 'comida' },
	{ word: 'RUA', clue: 'Via pública numa cidade', difficulty: 'easy', category: 'cidade' },
	{ word: 'MES', clue: 'Cada uma das 12 partes do ano', difficulty: 'easy', category: 'tempo' },
	{ word: 'FIM', clue: 'O oposto de início', difficulty: 'easy', category: 'geral' },
	{ word: 'VOZ', clue: 'Som produzido pela garganta humana', difficulty: 'easy', category: 'corpo' },
	{ word: 'LUZ', clue: 'Radiação visível que nos permite ver', difficulty: 'easy', category: 'natureza' },
	{ word: 'DOM', clue: 'Talento natural ou dia da semana', difficulty: 'easy', category: 'geral' },
	{ word: 'MAE', clue: 'Progenitora', difficulty: 'easy', category: 'familia' },
	{ word: 'PAI', clue: 'Progenitor', difficulty: 'easy', category: 'familia' },
	{ word: 'BEM', clue: 'O contrário de mal', difficulty: 'easy', category: 'geral' },
	{ word: 'MAL', clue: 'O contrário de bem', difficulty: 'easy', category: 'geral' },
	{ word: 'TEM', clue: 'Forma do verbo ter', difficulty: 'easy', category: 'geral' },

	{ word: 'CASA', clue: 'Lugar onde se vive', difficulty: 'easy', category: 'cidade' },
	{ word: 'GATO', clue: 'Felino doméstico', difficulty: 'easy', category: 'animais' },
	{ word: 'FOGO', clue: 'Combustão com chamas', difficulty: 'easy', category: 'natureza' },
	{ word: 'VIDA', clue: 'Existência de um ser', difficulty: 'easy', category: 'geral' },
	{ word: 'AMOR', clue: 'Sentimento de afeição profunda', difficulty: 'easy', category: 'geral' },
	{ word: 'NEVE', clue: 'Precipitação branca e gelada', difficulty: 'easy', category: 'natureza' },
	{ word: 'ONDA', clue: 'Movimento da água no mar', difficulty: 'easy', category: 'natureza' },
	{ word: 'ROSA', clue: 'Flor com espinhos', difficulty: 'easy', category: 'natureza' },
	{ word: 'MAPA', clue: 'Representação gráfica de um território', difficulty: 'easy', category: 'geral' },
	{ word: 'JOGO', clue: 'Atividade lúdica com regras', difficulty: 'easy', category: 'geral' },
	{ word: 'PATO', clue: 'Ave aquática que faz quá-quá', difficulty: 'easy', category: 'animais' },
	{ word: 'BOLA', clue: 'Objeto esférico para jogar', difficulty: 'easy', category: 'desporto' },
	{ word: 'REDE', clue: 'Malha de fios entrelaçados', difficulty: 'easy', category: 'geral' },
	{ word: 'NOTA', clue: 'Anotação escrita ou nota musical', difficulty: 'easy', category: 'geral' },
	{ word: 'ILHA', clue: 'Porção de terra rodeada de água', difficulty: 'easy', category: 'natureza' },
	{ word: 'LAGO', clue: 'Massa de água rodeada por terra', difficulty: 'easy', category: 'natureza' },
	{ word: 'VELA', clue: 'Cilindro de cera com pavio ou pano de barco', difficulty: 'easy', category: 'geral' },
	{ word: 'ARCO', clue: 'Estrutura curva ou arma de flechas', difficulty: 'easy', category: 'geral' },
	{ word: 'LOBO', clue: 'Canídeo selvagem', difficulty: 'easy', category: 'animais' },
	{ word: 'MESA', clue: 'Móvel com tampo para apoio', difficulty: 'easy', category: 'casa' },
	{ word: 'MEDO', clue: 'Sensação de receio ou pavor', difficulty: 'easy', category: 'geral' },
	{ word: 'VASO', clue: 'Recipiente para plantas ou flores', difficulty: 'easy', category: 'casa' },
	{ word: 'TEIA', clue: 'Rede tecida pela aranha', difficulty: 'easy', category: 'natureza' },
	{ word: 'OURO', clue: 'Metal precioso amarelo', difficulty: 'easy', category: 'geral' },
	{ word: 'NOITE', clue: 'Período escuro do dia', difficulty: 'easy', category: 'tempo' },
	{ word: 'PORTA', clue: 'Entrada de um edifício ou divisão', difficulty: 'easy', category: 'casa' },
	{ word: 'LIVRO', clue: 'Obra escrita com páginas', difficulty: 'easy', category: 'cultura' },
	{ word: 'PRAIA', clue: 'Faixa de areia junto ao mar', difficulty: 'easy', category: 'natureza' },
	{ word: 'TERRA', clue: 'Terceiro planeta do sistema solar', difficulty: 'easy', category: 'natureza' },
	{ word: 'VERDE', clue: 'Cor das folhas saudáveis', difficulty: 'easy', category: 'geral' },
	{ word: 'PEDRA', clue: 'Fragmento de rocha', difficulty: 'easy', category: 'natureza' },
	{ word: 'BRAVO', clue: 'Corajoso ou furioso', difficulty: 'easy', category: 'geral' },
	{ word: 'NAVIO', clue: 'Embarcação de grande porte', difficulty: 'easy', category: 'geral' },
	{ word: 'LEITE', clue: 'Bebida branca de origem animal', difficulty: 'easy', category: 'comida' },
	{ word: 'TIGRE', clue: 'Grande felino com riscas', difficulty: 'easy', category: 'animais' },
	{ word: 'ANDAR', clue: 'Piso de um edifício ou caminhar', difficulty: 'easy', category: 'geral' },

	// ─── Medium (5-8 letters) ───────────────────────────
	{ word: 'OCEANO', clue: 'Vasta extensão de água salgada entre continentes', difficulty: 'medium', category: 'natureza' },
	{ word: 'MUSICA', clue: 'Arte dos sons organizados', difficulty: 'medium', category: 'cultura' },
	{ word: 'JARDIM', clue: 'Espaço cultivado com plantas e flores', difficulty: 'medium', category: 'natureza' },
	{ word: 'PALCO', clue: 'Plataforma para espetáculos', difficulty: 'medium', category: 'cultura' },
	{ word: 'SONHO', clue: 'Imagens durante o sono ou aspiração', difficulty: 'medium', category: 'geral' },
	{ word: 'GRUTA', clue: 'Cavidade natural na rocha', difficulty: 'medium', category: 'natureza' },
	{ word: 'SERRA', clue: 'Cadeia montanhosa ou ferramenta de corte', difficulty: 'medium', category: 'natureza' },
	{ word: 'NUVEM', clue: 'Massa de vapor de água no céu', difficulty: 'medium', category: 'natureza' },
	{ word: 'PONTE', clue: 'Construção que liga duas margens', difficulty: 'medium', category: 'cidade' },
	{ word: 'ARENA', clue: 'Local de combates ou espetáculos', difficulty: 'medium', category: 'geral' },
	{ word: 'PERIGO', clue: 'Situação de risco ou ameaça', difficulty: 'medium', category: 'geral' },
	{ word: 'ESCUDO', clue: 'Proteção do guerreiro ou antiga moeda portuguesa', difficulty: 'medium', category: 'historia' },
	{ word: 'CINEMA', clue: 'Sala onde se projetam filmes', difficulty: 'medium', category: 'cultura' },
	{ word: 'FAROL', clue: 'Torre com luz para guiar navios', difficulty: 'medium', category: 'geral' },
	{ word: 'LENDA', clue: 'Narrativa tradicional com elementos fantásticos', difficulty: 'medium', category: 'cultura' },
	{ word: 'VULCAO', clue: 'Montanha que expele lava', difficulty: 'medium', category: 'natureza' },
	{ word: 'RELOGIO', clue: 'Instrumento que marca as horas', difficulty: 'medium', category: 'geral' },
	{ word: 'CASTELO', clue: 'Fortaleza medieval', difficulty: 'medium', category: 'historia' },
	{ word: 'ESPADA', clue: 'Arma branca de lâmina longa', difficulty: 'medium', category: 'historia' },
	{ word: 'PINTOR', clue: 'Artista que pinta quadros', difficulty: 'medium', category: 'cultura' },
	{ word: 'ALDEIA', clue: 'Pequena povoação rural', difficulty: 'medium', category: 'cidade' },
	{ word: 'RECEITA', clue: 'Instruções para cozinhar um prato', difficulty: 'medium', category: 'comida' },
	{ word: 'VIAGEM', clue: 'Deslocação a um lugar distante', difficulty: 'medium', category: 'geral' },
	{ word: 'ESPELHO', clue: 'Superfície que reflete imagens', difficulty: 'medium', category: 'casa' },
	{ word: 'HEROI', clue: 'Pessoa de grande coragem e nobreza', difficulty: 'medium', category: 'geral' },
	{ word: 'TESOURO', clue: 'Riqueza escondida ou muito valiosa', difficulty: 'medium', category: 'geral' },
	{ word: 'FLORESTA', clue: 'Grande extensão de árvores', difficulty: 'medium', category: 'natureza' },
	{ word: 'CAPITAO', clue: 'Líder de uma equipa ou navio', difficulty: 'medium', category: 'geral' },
	{ word: 'DRAGAO', clue: 'Criatura mítica que cospe fogo', difficulty: 'medium', category: 'fantasia' },
	{ word: 'TEMPLO', clue: 'Edifício sagrado para culto religioso', difficulty: 'medium', category: 'historia' },
	{ word: 'RAINHA', clue: 'Monarca feminina', difficulty: 'medium', category: 'geral' },
	{ word: 'COROA', clue: 'Adorno real para a cabeça', difficulty: 'medium', category: 'geral' },
	{ word: 'TRONO', clue: 'Assento cerimonial de um soberano', difficulty: 'medium', category: 'geral' },
	{ word: 'MUSEU', clue: 'Instituição que guarda obras de arte e artefactos', difficulty: 'medium', category: 'cultura' },
	{ word: 'ENIGMA', clue: 'Problema difícil de resolver, mistério', difficulty: 'medium', category: 'geral' },
	{ word: 'ANCORA', clue: 'Peça pesada que fixa o barco', difficulty: 'medium', category: 'geral' },
	{ word: 'PLANETA', clue: 'Corpo celeste que orbita uma estrela', difficulty: 'medium', category: 'ciencia' },
	{ word: 'BALEIA', clue: 'O maior mamífero do mundo', difficulty: 'medium', category: 'animais' },
	{ word: 'COMETA', clue: 'Corpo celeste com cauda brilhante', difficulty: 'medium', category: 'ciencia' },
	{ word: 'ESCADA', clue: 'Estrutura com degraus para subir', difficulty: 'medium', category: 'casa' },
	{ word: 'TOMATE', clue: 'Fruto vermelho usado em saladas e molhos', difficulty: 'medium', category: 'comida' },
	{ word: 'GENIO', clue: 'Pessoa de inteligência extraordinária', difficulty: 'medium', category: 'geral' },
	{ word: 'XADREZ', clue: 'Jogo de tabuleiro com peões, torres e reis', difficulty: 'medium', category: 'jogos' },
	{ word: 'MESTRE', clue: 'Aquele que ensina ou domina uma arte', difficulty: 'medium', category: 'geral' },
	{ word: 'PIRATA', clue: 'Bandido dos mares', difficulty: 'medium', category: 'historia' },
	{ word: 'SELVA', clue: 'Floresta tropical densa', difficulty: 'medium', category: 'natureza' },
	{ word: 'TRIBO', clue: 'Grupo social com cultura e líder comum', difficulty: 'medium', category: 'historia' },
	{ word: 'PISTA', clue: 'Indício ou caminho de corrida', difficulty: 'medium', category: 'geral' },
	{ word: 'BRUXA', clue: 'Mulher com poderes mágicos nas lendas', difficulty: 'medium', category: 'fantasia' },
	{ word: 'MAGIA', clue: 'Arte de produzir efeitos sobrenaturais', difficulty: 'medium', category: 'fantasia' },

	// ─── Hard (7-12 letters) ────────────────────────────
	{ word: 'LABIRINTO', clue: 'Estrutura complexa de caminhos entrecruzados', difficulty: 'hard', category: 'geral' },
	{ word: 'HORIZONTE', clue: 'Linha onde o céu parece tocar a terra', difficulty: 'hard', category: 'natureza' },
	{ word: 'ALQUIMIA', clue: 'Antiga prática de transformar metais em ouro', difficulty: 'hard', category: 'ciencia' },
	{ word: 'CONSTELACAO', clue: 'Grupo de estrelas que forma um padrão no céu', difficulty: 'hard', category: 'ciencia' },
	{ word: 'MANUSCRITO', clue: 'Documento escrito à mão', difficulty: 'hard', category: 'cultura' },
	{ word: 'BORBOLETA', clue: 'Inseto com asas coloridas', difficulty: 'hard', category: 'natureza' },
	{ word: 'PERGAMINHO', clue: 'Material antigo de escrita feito de pele animal', difficulty: 'hard', category: 'historia' },
	{ word: 'CREPUSCULO', clue: 'Luminosidade ténue ao anoitecer', difficulty: 'hard', category: 'natureza' },
	{ word: 'ESTRATEGIA', clue: 'Plano de ação para atingir um objetivo', difficulty: 'hard', category: 'geral' },
	{ word: 'CATEDRAL', clue: 'Igreja principal de uma diocese', difficulty: 'hard', category: 'historia' },
	{ word: 'AVALANCHE', clue: 'Massa de neve que desliza montanha abaixo', difficulty: 'hard', category: 'natureza' },
	{ word: 'FILOSOFIA', clue: 'Estudo do conhecimento e da existência', difficulty: 'hard', category: 'cultura' },
	{ word: 'TERREMOTO', clue: 'Tremor violento da crosta terrestre', difficulty: 'hard', category: 'natureza' },
	{ word: 'CAVALEIRO', clue: 'Guerreiro medieval a cavalo', difficulty: 'hard', category: 'historia' },
	{ word: 'AVENTURA', clue: 'Experiência emocionante e arriscada', difficulty: 'hard', category: 'geral' },
	{ word: 'UNIVERSO', clue: 'Totalidade do espaço, tempo e matéria', difficulty: 'hard', category: 'ciencia' },
	{ word: 'FRONTEIRA', clue: 'Limite entre dois países ou regiões', difficulty: 'hard', category: 'geral' },
	{ word: 'PENINSULA', clue: 'Porção de terra quase rodeada por água', difficulty: 'hard', category: 'natureza' },
	{ word: 'CONQUISTA', clue: 'Ato de conquistar ou vitória alcançada', difficulty: 'hard', category: 'historia' },
	{ word: 'CIDADELA', clue: 'Fortaleza dentro de uma cidade', difficulty: 'hard', category: 'historia' },
	{ word: 'GLADIADOR', clue: 'Lutador da Roma Antiga', difficulty: 'hard', category: 'historia' },
	{ word: 'OBELISCO', clue: 'Monumento alto em forma de pilar afilado', difficulty: 'hard', category: 'historia' },
	{ word: 'TELESCOPIO', clue: 'Instrumento ótico para observar astros', difficulty: 'hard', category: 'ciencia' },
	{ word: 'NAUFRAGIO', clue: 'Destruição de uma embarcação no mar', difficulty: 'hard', category: 'geral' },
	{ word: 'ECLIPSE', clue: 'Ocultação de um astro por outro', difficulty: 'hard', category: 'ciencia' },
	{ word: 'MITOLOGIA', clue: 'Conjunto de mitos de uma civilização', difficulty: 'hard', category: 'cultura' },
	{ word: 'FORTALEZA', clue: 'Construção militar defensiva', difficulty: 'hard', category: 'historia' },
	{ word: 'EXPEDIÇÃO', clue: 'Viagem organizada com um objetivo', difficulty: 'hard', category: 'geral' },
	{ word: 'MARINHEIRO', clue: 'Pessoa que trabalha no mar', difficulty: 'hard', category: 'geral' },
	{ word: 'MONUMENTO', clue: 'Obra construída em memória de algo notável', difficulty: 'hard', category: 'historia' },

	// ─── Portuguese specifics ───────────────────────────
	{ word: 'FADO', clue: 'Género musical tradicional português', difficulty: 'easy', category: 'portugal' },
	{ word: 'TEJO', clue: 'Rio que passa por Lisboa', difficulty: 'easy', category: 'portugal' },
	{ word: 'DOURO', clue: 'Rio famoso pelo vinho do Porto', difficulty: 'easy', category: 'portugal' },
	{ word: 'PORTO', clue: 'Segunda maior cidade de Portugal', difficulty: 'easy', category: 'portugal' },
	{ word: 'AZULEJO', clue: 'Peça cerâmica decorativa típica portuguesa', difficulty: 'medium', category: 'portugal' },
	{ word: 'BACALHAU', clue: 'Peixe salgado e seco, símbolo da gastronomia portuguesa', difficulty: 'medium', category: 'portugal' },
	{ word: 'PASTEIS', clue: 'Doces de massa folhada (de Belém, por exemplo)', difficulty: 'medium', category: 'portugal' },
	{ word: 'GUITARRA', clue: 'Instrumento de cordas usado no fado', difficulty: 'medium', category: 'portugal' },
	{ word: 'LUSITANO', clue: 'Relativo à antiga Lusitânia ou a Portugal', difficulty: 'hard', category: 'portugal' },
	{ word: 'CARAVELA', clue: 'Tipo de navio usado nos Descobrimentos', difficulty: 'hard', category: 'portugal' },
	{ word: 'SAUDADE', clue: 'Sentimento de falta intraduzível, típico português', difficulty: 'medium', category: 'portugal' },
	{ word: 'ALFAMA', clue: 'Bairro antigo e típico de Lisboa', difficulty: 'medium', category: 'portugal' },
	{ word: 'SINTRA', clue: 'Vila portuguesa com palácios e jardins', difficulty: 'easy', category: 'portugal' },
	{ word: 'ALGARVE', clue: 'Região sul de Portugal famosa pelas praias', difficulty: 'medium', category: 'portugal' },
	{ word: 'RIBEIRA', clue: 'Zona ribeirinha do Porto, Património Mundial', difficulty: 'medium', category: 'portugal' },

	// ─── Extra medium words ─────────────────────────────
	{ word: 'CODIGO', clue: 'Sistema de sinais ou linguagem secreta', difficulty: 'medium', category: 'geral' },
	{ word: 'ENIGMA', clue: 'Mistério ou charada difícil', difficulty: 'medium', category: 'geral' },
	{ word: 'MATRIZ', clue: 'Modelo original ou tabela matemática', difficulty: 'medium', category: 'ciencia' },
	{ word: 'CIFRA', clue: 'Código secreto ou número', difficulty: 'medium', category: 'geral' },
	{ word: 'ROBÔ', clue: 'Máquina autónoma programável', difficulty: 'medium', category: 'ciencia' },
	{ word: 'PIXEL', clue: 'Menor unidade de uma imagem digital', difficulty: 'medium', category: 'tecnologia' },
	{ word: 'LASER', clue: 'Feixe de luz concentrada', difficulty: 'medium', category: 'ciencia' },
	{ word: 'RADAR', clue: 'Sistema de deteção por ondas rádio', difficulty: 'medium', category: 'tecnologia' },
	{ word: 'NEXO', clue: 'Ligação ou conexão entre coisas', difficulty: 'easy', category: 'geral' },
	{ word: 'CORDA', clue: 'Fio grosso e resistente', difficulty: 'easy', category: 'geral' },
	{ word: 'ROCHA', clue: 'Massa sólida de mineral', difficulty: 'easy', category: 'natureza' },
	{ word: 'COFRE', clue: 'Caixa forte para guardar valores', difficulty: 'medium', category: 'geral' },
	{ word: 'CHAVE', clue: 'Instrumento para abrir fechaduras', difficulty: 'easy', category: 'geral' },
	{ word: 'SINAL', clue: 'Indicação ou marca visível', difficulty: 'easy', category: 'geral' },
	{ word: 'CAMPO', clue: 'Terreno aberto para cultivo ou desporto', difficulty: 'easy', category: 'natureza' },
	{ word: 'ROTA', clue: 'Caminho ou trajeto planeado', difficulty: 'easy', category: 'geral' },
	{ word: 'DUELO', clue: 'Combate entre duas pessoas', difficulty: 'medium', category: 'geral' },
	{ word: 'TROPA', clue: 'Grupo de soldados', difficulty: 'medium', category: 'historia' },
	{ word: 'HINO', clue: 'Cântico solene de uma nação ou grupo', difficulty: 'easy', category: 'cultura' },
	{ word: 'CENA', clue: 'Parte de uma peça de teatro ou situação', difficulty: 'easy', category: 'cultura' },
	{ word: 'PALMA', clue: 'Interior da mão ou tipo de árvore', difficulty: 'easy', category: 'geral' },
	{ word: 'GRADE', clue: 'Estrutura de barras paralelas', difficulty: 'easy', category: 'geral' },
	{ word: 'PRATA', clue: 'Metal precioso branco e brilhante', difficulty: 'easy', category: 'geral' },
	{ word: 'ATLAS', clue: 'Coleção de mapas num livro', difficulty: 'medium', category: 'cultura' },
	{ word: 'BRONZE', clue: 'Liga metálica de cobre e estanho', difficulty: 'medium', category: 'ciencia' },
	{ word: 'LITORAL', clue: 'Zona costeira junto ao mar', difficulty: 'medium', category: 'natureza' },
	{ word: 'BUSSOLA', clue: 'Instrumento de orientação magnética', difficulty: 'medium', category: 'ciencia' },
	{ word: 'ESCRITA', clue: 'Sistema de representação da linguagem', difficulty: 'medium', category: 'cultura' },
	{ word: 'LAREIRA', clue: 'Local da casa onde se faz fogo para aquecer', difficulty: 'medium', category: 'casa' },
];
